### ISSUE TITLE
win32/node6.10: "TypeError: Object.entries is not a function"

### ISSUE THREAD

**Issue by therealplato** [mjswensen/themer-hyper#1]
Hi, looking forward to trying this out! I'm new to yarn and themer. I'm running into an issue on windows that is not present when generating with themer-vim (see bottom of snippet and [`render()`](https://github.com/mjswensen/themer-hyper/blob/master/src/index.js#L9-L10)) Do I need a different node version or something?

```
$ yarn add themer themer-vim themer-hyper themer-colors-default 
...
$ yarn list themer themer-vim themer-hyper themer-colors-default themer-wallpaper-block-wave
yarn list v0.24.6
├─ themer-colors-default@1.0.1
├─ themer-hyper@2.0.0
├─ themer-vim@2.2.3
├─ themer-wallpaper-block-wave@1.0.2
└─ themer@2.2.0
Done in 0.25s.

there@pqrs MINGW64 ~/go/src/github.com/therealplato/plato-dotfiles (windows)
$ node -v
v6.10.0

there@pqrs MINGW64 ~/go/src/github.com/therealplato/plato-dotfiles (windows)
$ yarn vim
yarn vim v0.24.6
$ themer -c themer-colors-default -t themer-vim -o gen
resolving packages...
rendering templates...
writing files...
done!
Done in 0.48s.

there@pqrs MINGW64 ~/go/src/github.com/therealplato/plato-dotfiles (windows)
$ yarn hyper
yarn hyper v0.24.6
$ themer -c themer-colors-default -t themer-hyper -o gen
resolving packages...
rendering templates...
TypeError: Object.entries is not a function
error Command failed with exit code 1.

```

**Comment by mjswensen** [comment]
Hi @therealplato , good call on the node version—I bet if you try it with node 7.5 or higher it will work. (`Object.entries` is a relatively new feature in JavaScript.)

**Comment by therealplato** [comment]
thanks, i installed the "recommended for most users" version from nodejs.org. would you accept a PR that reverted to node 6 api's?

**Comment by mjswensen** [comment]
Absolutely! It should be as simple as replacing the dependency `babel-preset-latest` with `babel-preset-env` and specifying `node:6.11` in `.babelrc`. Then we can keep the `Object.entries` and it will simply transpile back to something that will work in node 6.

**Comment by mjswensen** [comment]
@therealplato : I was in this code doing some housekeeping so I ended up making the change real quick. If you upgrade to `v2.0.1` you should be good to go. Let me know if it doesn't work.

**Comment by therealplato** [comment]
Thanks @mjswensen!
I think with the `transform-runtime` plugin we can downgrade package.json's engine version? `yarn add themer-hyper@2.0.1` fails due to `engine: >=6.10`.

Local `git clone; yarn build; yarn link` generates working libs and successful theme generation after `yarn link themer-hyper` in my dotfiles folder.

**Comment by mjswensen** [comment]
Bummer! I put `6.11` since that is the version listed on [nodejs.org](https://nodejs.org/) as the LTS, but I'm realizing now as I look at your original post that you are on `6.10`. I'm happy to bump this one down if you want, but all the other `themer-` packages are listed at `6.11` as well, which would
 probably still cause you trouble—I assume the issue would go away if you upgrade node to `6.11`?

**Comment by therealplato** [comment]
No need to downgrade on my account, i'm happy with the `yarn link` solution. What are the advantages of a high target version?

**Comment by mjswensen** [comment]
No real advantages other than limiting the number of `node`s I have to test on 🙂  I figure support for the current LTS and up is probably sufficient for a project like this, where the code is probably not going to run in a large production environment. Especially with tools like `brew` or `nvm` that make it easy to get relatively new node versions.
